# Generated by Django 6.1 on 2026-08-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField()),
                ('qualification', models.CharField(choices=[('B.Tech', 'B. Tech'), ('MCA', 'MCA'), ('Graduation', 'Graduation'), ('Post-Graduation', 'Post-Graduation'), ('MBA', 'MBA'), ('Others', 'Others')], max_length=20)),
                ('skill_java', models.BooleanField(default=False)),
                ('skill_dotnet', models.BooleanField(default=False)),
                ('skill_python', models.BooleanField(default=False)),
                ('skill_database', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
